apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup
metadata:
  name: mysql-app-backup
  namespace: demo
spec:
  backupLocation: mysql-backup
  namespaces:
  - demo
  reclaimPolicy: Delete
  selectors:
    app: mysql
  preExecRule: mysql-pre-rule
  postExecRule: 
